### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by co-robo** [coala/coala-brackets#4]
Add a file named `ISSUE_TEMPLATE.md` which includes general information and guidelines for issue reporter, you can see ISSUE_TEMPLATE.md of `coala` repository for reference.
label: initiatives/gci
Opened by @Monal5031 at [gitter//Monal5031](https://gitter.im//Monal5031?at=59f33a82614889d475095f56)

**Comment by shikhar-scs** [comment]
If this issue is still up can I pls take this up?

**Comment by jayvdb** [comment]
This was supposed to be a Google Code-in task.  But it is done.
