### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by co-robo** [coala/coala-brackets#5]
Add a file named `PULL_REQUEST_TEMPLATE.md` which includes general information and guidelines for the author of Pull Request, you can see PULL_REQUEST_TEMPLATE.md of `coala` repository for reference.
label: initiatives/gci
Opened by @Monal5031 at [gitter//Monal5031](https://gitter.im//Monal5031?at=59f3662dd6c36fca31a4a5c4)

**Comment by shikhar-scs** [comment]
I would like to take on this. Can i be assigned this issue please.

**Comment by ghost** [comment]
Did u join the coala development group? I cant assign you this issue

**Comment by jayvdb** [comment]
This was supposed to be a GCI issue
